title: Christian Quade Howald # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/vocalizer/1.0.0/vocalizer.min.js"></script>
  <font size="+1">People call me</font>
  <font size="+3"><span class="vocalizer" data-source="auto"><font size="+1">Quade</font></span></font>
  <br><br>
  Social Media 
  <br><br>
  <link rel="stylesheet" href="../css/social-circles.min.css">
  <font size="-2"><a class="icon-linkedin social-button color" href="https://www.linkedin.com/in/quade-howald"></a></font>
  <font size="-2"><a class="icon-googleplus social-button color" href="mailto:quade.howald@gmail.com"></a></font>
  <font size="-2"><a class="icon-facebook social-button color" href="https://www.facebook.com/quade.howald"></a></font>
  <font size="-2"><a class="icon-instagram social-button color" href="http://instagram.com/quade.howald"></a></font>
  <br><br>
theme: jekyll-theme-minimal
google_analytics: UA-147457344-1 # your Google Analytics tracking ID here
